### ISSUE TITLE
Should we treat 0.x.y version changes as major?

### ISSUE THREAD

**Issue by Hades32** [product-os/renovate-config#11]
The PR https://github.com/product-os/transformer-worker/pull/494 updated a docker image from 0.18.1 to 0.19.0. NPM would consider this a major version change and the SemVer spec explicitly states that breaking changes might happen between 0.x releases.

Looking at this, I'm not sure if we need to change something or if this is a Renovate bug:
https://github.com/product-os/renovate-config/blob/3f0ad5c8ac419324b70bb329d66135778703998e/renovate.json#L38-L46

**Comment by joshbwlng** [comment]
@Hades32 It would still be a patch bump in our repos, but I guess what you're suggesting is not auto approving and merging. I honestly wasn't aware that the semver spec allows for breaking changes in minors. If that is the case I suspect we might should put these in a separate renovate group and require humans to approve these bumps.

**Comment by Hades32** [comment]
Yeah, it's a special case of 0.x.y versions. It also isn't implemented the same everywhere. NPM for example interprets 0.1 -> 0.2 as major and 0.1.1->0.1.2 as minor, whereas the spec makes no such guarantees for 0.x.y versions.

And yes, a manual approval is what I meant. TBH, there's still a chance that we would have missed that, but at least it would have been easier to find out what caused it
